apiVersion: apps/v1
kind: Deployment
metadata:
  name: jws-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jws-operator
  template:
    metadata:
      labels:
        name: jws-operator
    spec:
      serviceAccountName: jws-operator
      containers:
        - name: jws-operator
          image: quay.io/pitprok/jws-operator:v1.3.0-webapp-fix
          command:
            - jws-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "jws-operator"
